### ISSUE TITLE
How to configure Infinispan for distributed mode?

### ISSUE THREAD

**Issue by lukas-vlcek** [slaskawi/infinispan-wf-swarm-example#2]
Is it possible to configure Infinispan as a shared cache for service nodes?

Let's say I build the service first:

```
mvn clean package
```

Then I start two nodes:

```
java -jar -Dswarm.http.port=8080 target/wildfly-swarm-demo-swarm.jar
java -jar -Dswarm.http.port=8090 target/wildfly-swarm-demo-swarm.jar
```

Then I push data to cache via first node:

```
curl -X POST 'localhost:8080/rest/infinispan/cache' -d "test1"
```

Now, let's see if I can get this data from any service node:

```
curl -X GET 'localhost:8080/rest/infinispan/cache' -> [test1]
curl -X GET 'localhost:8090/rest/infinispan/cache' -> []
```

Seems the second node (8090) has its own Infinispan cache instance. Is sharing data via Infinispan supported use case?

**Comment by slaskawi** [comment]
After introducing https://github.com/slaskawi/infinispan-wf-swarm-example/pull/4, all caches should work on default transport (which is UDP). Please remember to use IPv4 stack (IPv6 might need some additional configuration: http://www.jgroups.org/manual/html_single/#d0e523

**Comment by lukas-vlcek** [comment]
Thanks, works nice!
